/** explainRepo — generates a repo architecture summary and opens it in a markdown preview */

import * as vscode from "vscode";
import * as os from "os";
import * as path from "path";
import * as fs from "fs/promises";
import { BackendClient } from "../services/backendClient";

const REPO_SUMMARY_FILENAME = ".repo-summary.md";

const REPO_EXPLAIN_QUESTION =
  "Describe the overall architecture of this project: main entry points, core modules, data flow, and key design patterns. Be comprehensive and well-structured.";

export function registerExplainRepo(
  context: vscode.ExtensionContext,
  client: BackendClient,
): vscode.Disposable {
  return vscode.commands.registerCommand(
    "repoAwareAI.explainRepo",
    async () => {
      await vscode.window.withProgress(
        {
          location: vscode.ProgressLocation.Notification,
          title: "Repo AI",
          cancellable: false,
        },
        async (progress) => {
          progress.report({ message: "Analyzing repository..." });
          try {
            const res = await client.query(REPO_EXPLAIN_QUESTION);

            const content = [
              "# Repository Architecture Summary",
              "",
              `> Generated by Repo-Aware AI on ${new Date().toLocaleString()}`,
              "",
              res.answer,
              "",
              "## Sources",
              ...res.sources.map((s) => `- \`${s}\``),
            ].join("\n");

            // Save to workspace root if available
            const workspaceRoot =
              vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
            const savePath = workspaceRoot
              ? path.join(workspaceRoot, REPO_SUMMARY_FILENAME)
              : path.join(os.tmpdir(), REPO_SUMMARY_FILENAME);

            await fs.writeFile(savePath, content, "utf-8");

            const uri = vscode.Uri.file(savePath);
            await vscode.commands.executeCommand("markdown.showPreview", uri);
          } catch (e) {
            void vscode.window.showErrorMessage(`Repo AI: ${String(e)}`);
          }
        },
      );
    },
  );
}
